apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: symfony-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/owllabsgit/test1-owl.git'
    targetRevision: main
    path: .  # car tous les YAML sont à la racine du repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
