apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: symfony=owllabsdocker/owllabs
    argocd-image-updater.argoproj.io/symfony.kustomize.image-name: owllabsdocker/owllabs
    argocd-image-updater.argoproj.io/symfony.allow-tags: regexp:^build-[a-zA-Z0-9-]+$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/owllabsgit/test1-owl.git
    targetRevision: main
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
