apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owllabs-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: test1-owl=docker.io/owllabsdocker/test1-owl
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/test1-owl.allow-tags: regexp:^([0-9a-f]{6,})$
    argocd-image-updater.argoproj.io/test1-owl.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/owllabsgit/test1-owl.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

