apiVersion: v1
kind: Service
metadata:
  name: symfony-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: symfony-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000 # Pick any port in the 30000-32767 range

