# k8s/symfony-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  namespace: dev
  labels:
    app: symfony-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: symfony-app
  template:
    meta
      labels:
        app: symfony-app
    spec:
      containers:
        - name: symfony
          image: owllabsdocker/test1-owl:latest
          imagePullPolicy: Always   # ✅ Add this line
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: symfony-env
          env:
            - name: DATABASE_URL
              value: mysql://root:root@mysql:3306/symfony
