apiVersion: v1
kind: Service
metadata:
  name: symfony-service
  namespace: test
spec:
  type: LoadBalancer  # Change to NodePort if your cluster doesn't have a LoadBalancer
  selector:
    app: symfony-app   # Matches your deployment's pod label
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 80   # Port in the container

