apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  namespace: test
  labels:
    app: symfony-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      containers:
        - name: symfony
          image: owllabsdocker/owllabs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: symfony-env
          env:
            - name: DATABASE_URL
              value: mysql://root:root@mysql:3306/symfony
      restartPolicy: Always

