apiVersion: v1
kind: PersistentVolumeClaim
meta
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Let K3s auto-provision with local-path
  # storageClassName: local-path  # optional (it's default)
