update:
  strategy: git
  git:
    branch: main
    commitMessage: "chore: update image tags for {{ .AppName }} ({{ .NewTag }})"

registries:
  - name: dockerhub
    prefix: docker.io
    api_url: https://registry-1.docker.io
    default: true

apps:
  - name: test1-owl-dev
    namespace: argocd
    images:
      - name: docker.io/owllabsdocker/test1-owl
        updatePolicy: newest-build
        allowTags: regexp:^([0-9a-f]{7,})$
        path: k8s/overlays/dev
        kustomize: {}
  - name: test1-owl-stg
    namespace: argocd
    images:
      - name: docker.io/owllabsdocker/test1-owl
        updatePolicy: newest-build
        allowTags: regexp:^([0-9a-f]{7,})$
        path: k8s/overlays/stg
        kustomize: {}
  - name: test1-owl-prod
    namespace: argocd
    images:
      - name: docker.io/owllabsdocker/test1-owl
        updatePolicy: newest-build
        allowTags: regexp:^([0-9a-f]{7,})$
        path: k8s/overlays/prod
        kustomize: {}

